# Generated by Django 5.1.3 on 2024-12-02 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('activa', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPrenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disenadores', to='usuarios.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Diseno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diseno_name', models.CharField(max_length=255)),
                ('diseno_date', models.DateField()),
                ('color', models.CharField(max_length=50)),
                ('talla', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disenador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.disenador')),
                ('prenda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.prenda')),
            ],
        ),
        migrations.AddField(
            model_name='prenda',
            name='tipo_prenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.tipoprenda'),
        ),
    ]
